### PR TITLE
version 3 - persistence

### PR DESCRIPTION
**Pull request by tr1ms**
- [x] added persistence :wink: 

Merge this please... :smile:

### CODE REVIEW

**Review by gordonnchy — COMMENTED** [review]
Looking Good! i would suggest to have a way to clear everything from localstorage sometimes!

**Review by gordonnchy — COMMENTED** [review]
also what about handling exceptions when localstorage is not supported in functions that u reference localstorage

- addTodo
- editTodo
- removeTodo

**Comment by tr1ms** [comment]
> also what about handling exceptions when localstorage is not supported in functions that u reference localstorage
> 
>     * addTodo
> 
>     * editTodo
> 
>     * removeTodo

`getTodos` does check for support

**Comment by gordonnchy** [comment]
> > also what about handling exceptions when localstorage is not supported in functions that u reference localstorage
> > ```
> > * addTodo
> > 
> > * editTodo
> > 
> > * removeTodo
> > ```
> 
> `getTodos` does check for support

yes `getTodos` does that but u still have a reference to localStorage in those function that can fire an exception because its not handled

**Comment by gordonnchy** [comment]
> > > also what about handling exceptions when localstorage is not supported in functions that u reference localstorage
> > > ```
> > > * addTodo
> > > 
> > > * editTodo
> > > 
> > > * removeTodo
> > > ```
> > 
> > 
> > `getTodos` does check for support
> 
> yes `getTodos` does that but u still have a reference to localStorage in those function that can fire an exception because its not handled

Maybe a simple test... make a supportStorage false and try to call one of the method either `addTodo`, `editTodo` or `removeTodo` and see the result

**Comment by gordonnchy** [comment]
> > > > also what about handling exceptions when localstorage is not supported in functions that u reference localstorage
> > > > ```
> > > > * addTodo
> > > > 
> > > > * editTodo
> > > > 
> > > > * removeTodo
> > > > ```
> > > 
> > > 
> > > `getTodos` does check for support
> > 
> > 
> > yes `getTodos` does that but u still have a reference to localStorage in those function that can fire an exception because its not handled
> 
> Maybe a simple test... make a storageSupport false and try to call one of the method either `addTodo`, `editTodo` or `removeTodo` and see the result

**Review by chrissglad — APPROVED** [review]
This is awesome work

**Pull request merged**
